packages:
  - .

ignoredBuiltDependencies:
  - sharp
  - unrs-resolver

overrides:
  '@isaacs/brace-expansion@<=5.0.0': '>=5.0.1'
  '@modelcontextprotocol/sdk@<1.25.2': '>=1.25.2'
  '@modelcontextprotocol/sdk@>=1.10.0 <=1.25.3': '>=1.26.0'
  ajv@<6.14.0: '>=6.14.0'
  ajv@>=7.0.0-alpha.0 <8.18.0: '>=8.18.0'
  diff@>=6.0.0 <8.0.3: '>=8.0.3'
  form-data@<2.5.4: '>=2.5.4'
  hono@<4.11.10: '>=4.11.10'
  hono@<4.11.4: '>=4.11.4'
  hono@<4.11.7: '>=4.11.7'
  minimatch@<10.2.1: '>=10.2.1'
  next@>=15.6.0-canary.0 <16.1.5: '>=16.1.5'
  next@>=16.0.0-beta.0 <16.1.5: '>=16.1.5'
  next@>=16.1.0-canary.0 <16.1.5: '>=16.1.5'
  qs@<6.14.1: '>=6.14.1'
  qs@>=6.7.0 <=6.14.1: '>=6.14.2'
  tough-cookie@<4.1.3: '>=4.1.3'
  xml2js@<0.5.0: '>=0.5.0'
